# version: '3.9'

# services:
#   web:
#     image: 'sudip/node-todo-test:latest'
#     ports:
#       - "8000:8000"
version: '3'

services:
  dockerexpress:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      -  /node_modules  
    environment:
      - PORT=8000 